### ISSUE TITLE
Suggestion pour la méthode de merge des PR

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/Py-Insee-Data#14]
#13 is my first PR on this repo. I see that all merge methods allowed by Github are available. @hadrilec I recommend you to go in `Settings` and only enable  `Squash and merge commits`.

`Squash and merge` method is preferrable because evolutions on a `master` branch with hundreds of commits are harder to grasp. By squashing commits before merging, we will have a better understanding of changes in `master`

**Comment by hadrilec** [comment]
Thanks for the advice. Done !
