### ISSUE TITLE
Add history file

### ISSUE THREAD

**Issue by MelineeTS** [InseeFrLab/Py-Insee-Data#21]
A HISTORY (or NEWS or CHANGELOG) file describing changes associated with each version makes it easier for users to see what’s changing in the package and how it might impact their workflow

**Comment by hadrilec** [comment]
Indeed this was missing. Done! [link](https://github.com/InseeFrLab/Py-Insee-Data/commit/903e9badbe953737368ec4ac0b87eaeb7584fc95)
