### ISSUE TITLE
Managing key secret pair in a yaml file rather than plainly in .py files

### ISSUE THREAD

**Issue by raphaeleadjerad** [InseeFrLab/Py-Insee-Data#4]
- create a `secrets.yaml` file
- add it to .gitignore
- tell people to put their key-secret pair in it
- all code using the pair should load the yaml instead of writing it, as follows:

```python
import yaml
with open("secrets.yaml", "r") as creds:
        secrets = yaml.safe_load(creds) 
```

**Comment by hadrilec** [comment]
Done  #12
